Repository SkillsFundingAgency/das-apply-service, pull requests merged in 2019-05, with the labels that each got.

#159 ON-1821 Added test to scan for authorize attributes on Controllers
  src/SFA.DAS.ApplyService.InternalApi.UnitTests/ControllerAuthorizeAttributeTests.cs
  src/SFA.DAS.ApplyService.InternalApi.UnitTests/SFA.DAS.ApplyService.InternalApi.UnitTests.csproj
  src/SFA.DAS.ApplyService.InternalApi/Controllers/AccountController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/ApplicationController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/EmailTemplateController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/FileController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/FinancialController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/OrganisationController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/OrganisationSearchController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/QuestionOptionsController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/ReviewController.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/StandardSearchController.cs
  src/SFA.DAS.ApplyService.InternalApi/Startup.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/ControllerAuthorizeAttributeTests.cs
  src/SFA.DAS.ApplyService.Web/Controllers/ImportController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/MigrateUsersController.cs
Labels: Tested

#149 ON-1791 - Show standard name on Assessor Staff application dashboard
  src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
Labels: Public-Beta, Tested

#145 ON-1781- Auto populate feedback with comment provided in FHA if grade…
  src/SFA.DAS.ApplyService.Application/Apply/Financial/UpdateGradeHandler.cs
Labels: Public-Beta, Tested

#167 ON-1834 Added extra security headers as per security scan recommendation
  src/SFA.DAS.ApplyService.InternalApi/Infrastructure/SecurityHeaderExtensions.cs
  src/SFA.DAS.ApplyService.InternalApi/Startup.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/SecurityHeadersExtensions.cs
  src/SFA.DAS.ApplyService.Web/Startup.cs
Labels: Tested

#156 On 1814 premable confirm org type
  src/SFA.DAS.ApplyService.InternalApi/Controllers/OrganisationSearchController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/OrganisationSearchController.cs
  src/SFA.DAS.ApplyService.Web/Views/OrganisationSearch/Results.cshtml
Labels: Tested

#171 ON-1860 - Fixed incorrect RequestedFeedbackAnswered check
  src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
Labels: Requires testing

#147 Fixed incorrect log error message
  src/SFA.DAS.ApplyService.EmailService/EmailService.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/ClaimsPrincipalExtensions.cs
Labels: Tested

#169 ON-1689 Using defined framework constants consistently for establishing a login session.
  src/SFA.DAS.ApplyService.Web/Controllers/UsersController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/AuthorizationStartupExtensions.cs
  src/SFA.DAS.ApplyService.Web/Startup.cs
Labels: Tested

#165 ON-1638 Enforce exact UK date format into correct day / month / year input; outputting correct UK date format all previously entered dates.
  src/SFA.DAS.ApplyService.Application/Apply/Validation/DateNotInFutureValidator.cs
  src/SFA.DAS.ApplyService.Application/Apply/Validation/DateValidator.cs
  src/SFA.DAS.ApplyService.Web/Controllers/QuestionViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Controls/_Date.cshtml
Labels: Tested

#172 On 1811 split name field on two pages
  src/WorkflowLatest.sql
Labels: Tested

#178 The validation message is now shown on the view when less than 2 characters are entered in a search for standard.
  src/SFA.DAS.ApplyService.Web/Controllers/StandardController.cs
Labels: Tested

#150 ON-1793 - Action all requested feedback before submitting
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/UpdatePageAnswersHandlerTestBase.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_answer_value_not_changed.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_answer_with_further_answer_is_provided.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_no_answers_on_multiple_answers_page_with_existing_answers_are_provided.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_valid_answer_for_conditional_question_is_provided.cs
  src/SFA.DAS.ApplyService.Application/Apply/UpdatePageAnswers/UpdatePageAnswersHandler.cs
  src/SFA.DAS.ApplyService.Web/Controllers/ApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Views/Application/Feedback.cshtml
Labels: Tested

#181 On 1793 action feedback before submitting
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/UpdatePageAnswersHandlerTestBase.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_all_requested_feedback_is_completed.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_all_requested_feedback_is_not_completed.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_answer_value_not_changed.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_no_answers_on_multiple_answers_page_with_existing_answers_are_provided.cs
  src/SFA.DAS.ApplyService.Application/Apply/UpdatePageAnswers/UpdatePageAnswersHandler.cs
Labels: Tested

#173 ON-1873 - Upsert security headers
  src/SFA.DAS.ApplyService.InternalApi/Infrastructure/SecurityHeaderExtensions.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/SecurityHeadersExtensions.cs
Labels: Requires testing

#184 On 1753 additional copy change
  src/SFA.DAS.ApplyService.Web/Views/Application/Standard/FindStandard.cshtml
Labels: Tested
