Repository SkillsFundingAgency/das-apply-service, pull requests merged in 2019-12, with the labels that each got.

#370 tasklist status update
  src/SFA.DAS.ApplyService.Web/Views/Roatp/TaskList.cshtml
Labels: Tested

#357 APR-1020 change content and flow for terms and conditions acceptance page
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationPreambleController.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/ConditionsOfAcceptanceViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Roatp/TermsAndConditions.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/TermsAndConditionsNotAgreed.cshtml
Labels: Awaiting PO Review

#363 Apr 965 service start page
  src/SFA.DAS.ApplyService.Web/Controllers/UsersController.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/ExistingAccountViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Home/Index.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Users/CreateAccount.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Users/ExistingAccount.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Users/InviteSent.cshtml
Labels: Awaiting PO Review

#345 Apr 502 get help with this question
  src/SFA.DAS.ApplyService.Application.UnitTests/GetHelpWithQuestionEmailServiceTests.cs
  src/SFA.DAS.ApplyService.Application.UnitTests/SFA.DAS.ApplyService.Application.UnitTests.csproj
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/RoatpPreambleQuestionBuilder.cs
  src/SFA.DAS.ApplyService.Application/Email/Consts/EmailTemplateName.cs
  src/SFA.DAS.ApplyService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.ApplyService.Domain/Roatp/GetHelpWithQuestion.cs
  src/SFA.DAS.ApplyService.EmailService/EmailService.cs
  src/SFA.DAS.ApplyService.EmailService/GetHelpWithQuestionEmailService.cs
  src/SFA.DAS.ApplyService.EmailService/IEmailTemplateClient.cs
  src/SFA.DAS.ApplyService.EmailService/IGetHelpWithQuestionEmailService.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationPreambleControllerTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpWhosInControlApplicationControllerTests.cs
  src/SFA.DAS.ApplyService.Web/Controllers/IPageViewModel.cs
  src/SFA.DAS.ApplyService.Web/Controllers/PageViewModel.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/GetHelpController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationPreambleController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplyControllerBase.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpWhosInControlApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpYourOrganisationApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/EmailTemplateClient.cs
  src/SFA.DAS.ApplyService.Web/SFA.DAS.ApplyService.Web.csproj
  src/SFA.DAS.ApplyService.Web/Startup.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/ChangeProviderRouteViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/EmployerLevyStatusViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/EmployerProviderContinueApplicationViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/SearchByUkprnViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/SelectApplicationRouteViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/AddEditPeopleInControlViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/ConfirmDirectorsPscsViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/ConfirmPartnersViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/ConfirmPartnershipTypeViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/ConfirmPeopleInControlViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/ConfirmRemovePersonInControlViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/ConfirmTrusteesDateOfBirthViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/ConfirmTrusteesViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/SoleTradeDobViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/WhosInControl/SoleTraderOrPartnershipViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Index.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ConfirmLevyStatus.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/EnterApplicationUkprn.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/GetHelpWithThisQuestion.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/IneligibleNonLevy.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ProviderAlreadyOnRegister.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/SelectApplicationRoute.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/AddPartner.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/AddPeopleInControl.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/AddSoleTradeDob.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmDirectorsPscs.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmPartners.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmPeopleInControl.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmPscRemoval.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmTrusteesDob.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmTrusteesNoDob.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/EditPartner.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/EditPeopleInControl.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/PartnershipType.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/SoleTraderOrPartnership.cshtml
  src/SFA.DAS.ApplyService.Web/wwwroot/stylesheets/application.css
Labels: BlockedByTesters

#355 Apr 941 submit application
  src/SFA.DAS.ApplyService.Application/Apply/IApplyRepository.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/GetApplicationDataHandler.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/GetApplicationDataRequest.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/GetNextApplicationReferenceHandler.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/GetNextApplicationReferenceRequest.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/RoatpPreambleQuestionBuilder.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/SubmitApplicationHandler.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/SubmitApplicationRequest.cs
  src/SFA.DAS.ApplyService.Application/Email/Consts/EmailTemplateName.cs
  src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
  src/SFA.DAS.ApplyService.Data/DapperTypeHandlers/RoatpApplicationDataHandler.cs
  src/SFA.DAS.ApplyService.Database/SFA.DAS.ApplyService.Database.sqlproj
  src/SFA.DAS.ApplyService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.ApplyService.Database/Sequences/RoatpAppReferenceSequence.sql
  src/SFA.DAS.ApplyService.Domain/Entities/RoatpApplicationData.cs
  src/SFA.DAS.ApplyService.Domain/Roatp/ApplicationSubmitConfirmation.cs
  src/SFA.DAS.ApplyService.EmailService/GetHelpWithQuestionEmailService.cs
  src/SFA.DAS.ApplyService.EmailService/ISubmitApplicationConfirmationEmailService.cs
  src/SFA.DAS.ApplyService.EmailService/NotificationApiEmailService.cs
  src/SFA.DAS.ApplyService.EmailService/SubmitApplicationConfirmationEmailService.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.InternalApi/web.config
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationControllerTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/PageViewModelTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Services/RoatpTaskListWorkflowServiceTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/TaskListViewModelTests.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationPreambleController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplyControllerBase.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpShutterPagesController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/IRoatpApiClient.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/RoatpApiClient.cs
  src/SFA.DAS.ApplyService.Web/Services/IRoatpTaskListWorkflowService.cs
  src/SFA.DAS.ApplyService.Web/Services/RoatpTaskListWorkflowService.cs
  src/SFA.DAS.ApplyService.Web/Startup.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/IPageViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/PageViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/QuestionViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/ApplicationSummaryViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/SubmitApplicationViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/TaskListViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/SequenceViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/StandardViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Application/Feedback.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Index.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/MultipleAnswers.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/Sequence.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationSubmitted.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/GetHelpWithThisQuestion.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/SubmitApplication.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/TaskList/FinishSequence.cshtml
Labels: TestInProgress

#375 QnA validation enhancements
  src/SFA.DAS.ApplyService.Configuration/ConfigurationService.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpWhosInControlApplicationControllerTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/QuestionPropertyTokeniserTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Services/ProcessPageFlowServiceTests.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpWhosInControlApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/ApiError.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/IQnaApiClient.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/QnaApiClient.cs
Labels: Awaiting PO Review

#364 Apr 911 enter course directory contact
  src/SFA.DAS.ApplyService.Web/Services/RoatpTaskListWorkflowService.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/PageViewModel.cs
  src/SFA.DAS.ApplyService.Web/appsettings.json
Labels: Tested

#334 APR-791 - Evaluating Apprenticeship Training
  src/SFA.DAS.ApplyService.Web/appsettings.json
Labels: Awaiting PO Review

#358 Apr 991 check existing applications
  src/SFA.DAS.ApplyService.Application/Apply/IApplyRepository.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/GetExistingApplicationStatusHandler.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/GetExistingApplicationStatusRequest.cs
  src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
  src/SFA.DAS.ApplyService.Domain/Roatp/ApplicationStatus.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/ApplicationController.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationPreambleControllerTests.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationPreambleController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpShutterPagesController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/ApplicationApiClient.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/IApplicationApiClient.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/ExistingApplicationViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationInProgress.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationPreviouslySubmitted.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationSubmitted.cshtml
Labels: TestInProgress

#378 APR-793 criminal and compliance checks
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/RoatpPreambleQuestionBuilder.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationControllerTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/PageViewModelTests.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/PageViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/TaskListViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Index.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/PeopleInControlComponent.cshtml
  src/SFA.DAS.ApplyService.Web/appsettings.json
Labels: Tested
