Repository SkillsFundingAgency/das-apply-service, pull requests merged in 2020-04, with the labels that each got.

#489 APR-1368 - apply cookie banner
  src/SFA.DAS.ApplyService.Web/Controllers/HomeController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/SecurityHeadersExtensions.cs
  src/SFA.DAS.ApplyService.Web/Views/Home/CookieDetails.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Home/Cookies.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Shared/_Layout.cshtml
  src/SFA.DAS.ApplyService.Web/bundleconfig.json
  src/SFA.DAS.ApplyService.Web/wwwroot/javascripts/application.js
  src/SFA.DAS.ApplyService.Web/wwwroot/javascripts/cookie-banner/_cookieBanner.js
  src/SFA.DAS.ApplyService.Web/wwwroot/javascripts/cookie-banner/_cookieSettings.js
  src/SFA.DAS.ApplyService.Web/wwwroot/javascripts/cookie-banner/_cookies.js
  src/SFA.DAS.ApplyService.Web/wwwroot/javascripts/cookie-banner/das-cookie-banner.js
  src/SFA.DAS.ApplyService.Web/wwwroot/javascripts/das-cookie-banner.js
  src/SFA.DAS.ApplyService.Web/wwwroot/stylesheets/application.css
Labels: Tested

#468 APR-1396 Stop Inactive Pages being accessed
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
Labels: Awaiting PO Review

#505 APR-1294 - RoATP Gateway : Register Checks - RoATP
  src/SFA.DAS.ApplyService.InternalApi.UnitTests/GatewayRegisterChecksControllerTests.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/GatewayRegisterChecksController.cs
Labels: Awaiting PO Review

#515 APR-1345 bug fixed and coverage added
  src/SFA.DAS.ApplyService.Web.UnitTests/TaskListViewModelTests.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/Roatp/TaskListViewModel.cs
Labels: TestInProgress
