Repository SkillsFundingAgency/das-apply-service, pull requests merged in 2020-02, with the labels that each got.

#385 APR-792 delivering apprenticeship training
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/IQnaApiClient.cs
  src/SFA.DAS.ApplyService.Web/appsettings.json
Labels: Tested

#407 APR-1213 correctly save further questions
  src/SFA.DAS.ApplyService.Web.IntegrationTests/SFA.DAS.ApplyService.Web.IntegrationTests.csproj
  src/SFA.DAS.ApplyService.Web.UnitTests/SFA.DAS.ApplyService.Web.UnitTests.csproj
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.Web/SFA.DAS.ApplyService.Web.csproj
  src/SFA.DAS.ApplyService.Web/ViewModels/PageViewModel.cs
  src/SFA.DAS.ApplyService.Web/ViewModels/QuestionViewModel.cs
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/MultipleAnswers.cshtml
Labels: Tested

#409 APR-1222 fixed back link for confirm partners page
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpWhosInControlApplicationController.cs
Labels: Requires testing

#425 APR-1197 - Add RoTO question back into sequence 3
  src/SFA.DAS.ApplyService.Web/appsettings.json
Labels: Private Beta, TestInProgress

#431 Apr 1318 management hierarchy fixes
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpManagementHierarchyController.cs
  src/SFA.DAS.ApplyService.Web/Validators/ManagementHierarchyValidator.cs
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ManagementHierarchy/AddManagementHierarchy.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ManagementHierarchy/ConfirmManagementHierarchy.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ManagementHierarchy/ConfirmManagementHierarchyRemoval.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ManagementHierarchy/EditManagementHierarchy.cshtml
Labels: Private Beta, Requires testing

#444 APR-961 - Remove link to survey in phase banner. Update application submitted p…
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationSubmitted.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Shared/_Layout.cshtml
Labels: Private Beta, Superbranch

#439 APR-1353 - Shutter page
  src/SFA.DAS.ApplyService.Web/Views/Home/Error.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationSubmitted.cshtml
Labels: Private Beta, Superbranch

#434 APR-1284 PYA Content Update
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpWhosInControlApplicationController.cs
Labels: Private Beta, Tested

#412 APR-1152 store section exemption rules to ApplyData JSON
  src/SFA.DAS.ApplyService.Application/Apply/Start/StartApplicationHandler.cs
  src/SFA.DAS.ApplyService.Application/Apply/Start/StartApplicationRequest.cs
  src/SFA.DAS.ApplyService.Domain/Entities/Apply.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationControllerTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationPreambleControllerTests.cs
  src/SFA.DAS.ApplyService.Web.UnitTests/Services/RoatpTaskListWorkflowServiceTests.cs
  src/SFA.DAS.ApplyService.Web/AutoMapper/RoatpSectionOverrideProfile.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs
  src/SFA.DAS.ApplyService.Web/MappingStartup.cs
  src/SFA.DAS.ApplyService.Web/appsettings.json
Labels: Private Beta, Requires testing

#457 APR-1372 - Update copy on app. submitted page and add in missing </div> on Exist…
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationSubmitted.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Users/ExistingAccount.cshtml
Labels: Requires testing

#451 APR-1331 : Remove back links
  src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Index.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/PagesWithSections.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/Section.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/SectionQuestions.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/Standard/ConfirmStandard.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Application/Standard/FindStandardResults.cshtml
  src/SFA.DAS.ApplyService.Web/Views/OrganisationSearch/Confirm.cshtml
  src/SFA.DAS.ApplyService.Web/Views/OrganisationSearch/Type.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationInProgress.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationPreviouslySubmitted.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ChangeUkprn.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/CharityCommissionNotAvailable.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/CharityNotFound.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ChosenToRemainOnRegister.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/CompaniesHouseNotAvailable.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/CompanyNotFound.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ConfirmChangeRoute.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ConfirmLevyStatus.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ConfirmOrganisation.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/EnterApplicationUkprn.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/IneligibleNonLevy.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ManagementHierarchy/AddManagementHierarchy.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ManagementHierarchy/ConfirmManagementHierarchyRemoval.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ManagementHierarchy/EditManagementHierarchy.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/NonLevyAbandonedApplication.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/ProviderAlreadyOnRegister.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/SelectApplicationRoute.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/SubmitApplication.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/TermsAndConditionsNotAgreed.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/UkprnNotFound.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/UkrlpNotAvailable.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/AddPartner.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/AddPeopleInControl.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/AddSoleTradeDob.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmDirectorsPscs.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmPartners.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmPeopleInControl.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmPscRemoval.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmTrusteesDob.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/ConfirmTrusteesNoDob.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/EditPartner.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/EditPeopleInControl.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/PartnershipType.cshtml
  src/SFA.DAS.ApplyService.Web/Views/Roatp/WhosInControl/SoleTraderOrPartnership.cshtml
Labels: Requires testing

#456 APR-1361 - Update ApplyDetails.ProviderRoute when changing Provider Route
  src/SFA.DAS.ApplyService.Application/Apply/IApplyRepository.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/ChangeProviderRouteHandler.cs
  src/SFA.DAS.ApplyService.Application/Apply/Roatp/ChangeProviderRouteRequest.cs
  src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
  src/SFA.DAS.ApplyService.InternalApi/Controllers/ApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationPreambleController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/ApplicationApiClient.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/IApplicationApiClient.cs
Labels: Tested

#466 APR-1419 Whitelist private beta users
  src/SFA.DAS.ApplyService.Application/Apply/IApplyRepository.cs
  src/SFA.DAS.ApplyService.Application/Apply/WhitelistedProviders/CheckIsUkprnWhitelistedHandler.cs
  src/SFA.DAS.ApplyService.Application/Apply/WhitelistedProviders/CheckIsUkprnWhitelistedRequest.cs
  src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
  src/SFA.DAS.ApplyService.Database/SFA.DAS.ApplyService.Database.sqlproj
  src/SFA.DAS.ApplyService.Database/Script.PostDeployment1.sql
  src/SFA.DAS.ApplyService.Database/Tables/WhitelistedProviders.sql
  src/SFA.DAS.ApplyService.InternalApi/Controllers/WhitelistedProvidersController.cs
  src/SFA.DAS.ApplyService.InternalApi/SFA.DAS.ApplyService.InternalApi.csproj
  src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationPreambleControllerTests.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationPreambleController.cs
  src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpWhosInControlApplicationController.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/ApplicationApiClient.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/IWhitelistedProvidersApiClient.cs
  src/SFA.DAS.ApplyService.Web/Infrastructure/WhitelistedProvidersApiClient.cs
  src/SFA.DAS.ApplyService.Web/Resources/UkprnValidationMessages.Designer.cs
  src/SFA.DAS.ApplyService.Web/Resources/UkprnValidationMessages.resx
  src/SFA.DAS.ApplyService.Web/Services/TabularDataRepository.cs
  src/SFA.DAS.ApplyService.Web/Startup.cs
  src/SFA.DAS.ApplyService.Web/Validators/IUkprnWhitelistValidator.cs
  src/SFA.DAS.ApplyService.Web/Validators/UkprnWhitelistValidator.cs
Labels: Requires testing

#452 Apr 1358 exempt sections
  src/SFA.DAS.ApplyService.Web/appsettings.json
Labels: Requires testing
